-- Add push tokens and notification cooldown tracking

create table if not exists public.push_tokens (
  id bigint generated by default as identity primary key,
  auth_user_id uuid references auth.users(id) on delete cascade,
  token text not null unique,
  platform text,
  is_active boolean not null default true,
  last_seen timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create table if not exists public.notification_cooldowns (
  event_key text primary key,
  last_sent_at timestamptz not null default now()
);

alter table public.push_tokens enable row level security;
alter table public.notification_cooldowns enable row level security;

create policy "Authenticated users can manage push tokens" on public.push_tokens
  for all using (auth.uid() is not null);

create policy "Authenticated users can manage notification cooldowns" on public.notification_cooldowns
  for all using (auth.uid() is not null);
