-- Migration script to add role-based access control
-- Run this in Supabase SQL Editor if you have existing data
-- This script handles both existing and missing tables

-- Step 1: Create the enum type
DO $$ BEGIN
  CREATE TYPE user_role AS ENUM ('viewer', 'editor', 'administrator');
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;

-- Step 1.5: Create missing tables if they don't exist
-- This ensures we have all required tables before modifying them
DO $$
DECLARE
  horses_id_type text;
  treatments_id_type text;
BEGIN
  SELECT data_type INTO horses_id_type
  FROM information_schema.columns
  WHERE table_schema = 'public' AND table_name = 'horses' AND column_name = 'id';

  IF horses_id_type IS NULL THEN
    horses_id_type := 'bigint';
  END IF;

  SELECT data_type INTO treatments_id_type
  FROM information_schema.columns
  WHERE table_schema = 'public' AND table_name = 'treatments' AND column_name = 'id';

  IF treatments_id_type IS NULL THEN
    treatments_id_type := 'bigint';
  END IF;

  -- HORSES TABLE
  IF NOT EXISTS (SELECT 1 FROM pg_tables WHERE schemaname = 'public' AND tablename = 'horses') THEN
    IF horses_id_type = 'uuid' THEN
      EXECUTE '
        CREATE TABLE public.horses (
          id uuid primary key default gen_random_uuid(),
          name text not null,
          breed text,
          age integer,
          gender text check (gender in (''Mare'', ''Gelding'')),
          color text,
          photo_url text,
          health_status text not null default ''healthy''
            check (health_status in (''healthy'', ''needs_attention'', ''critical'', ''palliative'')),
          arrival_date date,
          left_eye text check (left_eye in (''Missing'', ''Blind'', ''Glaucoma'', ''Injured'') or left_eye is null),
          right_eye text check (right_eye in (''Missing'', ''Blind'', ''Glaucoma'', ''Injured'') or right_eye is null),
          heart_murmur boolean not null default false,
          cushings_positive boolean not null default false,
          heaves boolean not null default false,
          anhidrosis boolean not null default false,
          shivers boolean not null default false,
          bites boolean not null default false,
          kicks boolean not null default false,
          difficult_to_catch boolean not null default false,
          problem_with_needles boolean not null default false,
          problem_with_farrier boolean not null default false,
          sedation_for_farrier boolean not null default false,
          requires_extra_feed boolean not null default false,
          requires_extra_mash boolean not null default false,
          seen_by_vet boolean not null default false,
          seen_by_farrier boolean not null default false,
          military_police_horse boolean not null default false,
          ex_racehorse boolean not null default false,
          deceased boolean not null default false,
          date_of_death date,
          grooming_day text,
          pasture text,
          behavior_notes text,
          regular_treatment boolean not null default false,
          medical_notes text,
          created_at timestamptz not null default now(),
          updated_at timestamptz not null default now(),
          last_updated timestamptz not null default now(),
          updated_by uuid
        )';
    ELSE
      EXECUTE '
        CREATE TABLE public.horses (
          id bigint generated by default as identity primary key,
          name text not null,
          breed text,
          age integer,
          gender text check (gender in (''Mare'', ''Gelding'')),
          color text,
          photo_url text,
          health_status text not null default ''healthy''
            check (health_status in (''healthy'', ''needs_attention'', ''critical'', ''palliative'')),
          arrival_date date,
          left_eye text check (left_eye in (''Missing'', ''Blind'', ''Glaucoma'', ''Injured'') or left_eye is null),
          right_eye text check (right_eye in (''Missing'', ''Blind'', ''Glaucoma'', ''Injured'') or right_eye is null),
          heart_murmur boolean not null default false,
          cushings_positive boolean not null default false,
          heaves boolean not null default false,
          anhidrosis boolean not null default false,
          shivers boolean not null default false,
          bites boolean not null default false,
          kicks boolean not null default false,
          difficult_to_catch boolean not null default false,
          problem_with_needles boolean not null default false,
          problem_with_farrier boolean not null default false,
          sedation_for_farrier boolean not null default false,
          requires_extra_feed boolean not null default false,
          requires_extra_mash boolean not null default false,
          seen_by_vet boolean not null default false,
          seen_by_farrier boolean not null default false,
          military_police_horse boolean not null default false,
          ex_racehorse boolean not null default false,
          deceased boolean not null default false,
          date_of_death date,
          grooming_day text,
          pasture text,
          behavior_notes text,
          regular_treatment boolean not null default false,
          medical_notes text,
          created_at timestamptz not null default now(),
          updated_at timestamptz not null default now(),
          last_updated timestamptz not null default now(),
          updated_by bigint
        )';
    END IF;
  END IF;

  -- MEDICAL RECORDS TABLE
  IF NOT EXISTS (SELECT 1 FROM pg_tables WHERE schemaname = 'public' AND tablename = 'medical_records') THEN
    EXECUTE format('
      CREATE TABLE public.medical_records (
        id bigint generated by default as identity primary key,
        horse_id %s not null,
        record_type text not null default ''checkup''
          check (record_type in (''checkup'', ''vaccination'', ''treatment'', ''surgery'', ''other'')),
        description text not null,
        vet_name text not null,
        date date not null,
        next_followup date,
        notes text,
        created_at timestamptz not null default now()
      )', horses_id_type);
  END IF;

  -- TREATMENTS TABLE
  IF NOT EXISTS (SELECT 1 FROM pg_tables WHERE schemaname = 'public' AND tablename = 'treatments') THEN
    IF treatments_id_type = 'uuid' THEN
      EXECUTE '
        CREATE TABLE public.treatments (
          id uuid primary key default gen_random_uuid(),
          type text not null,
          frequency text,
          created_at timestamptz not null default now(),
          last_updated timestamptz not null default now(),
          updated_by uuid
        )';
    ELSE
      EXECUTE '
        CREATE TABLE public.treatments (
          id bigint generated by default as identity primary key,
          type text not null,
          frequency text,
          created_at timestamptz not null default now(),
          last_updated timestamptz not null default now(),
          updated_by bigint
        )';
    END IF;
  END IF;

  -- ACTION TAKEN TABLE
  IF NOT EXISTS (SELECT 1 FROM pg_tables WHERE schemaname = 'public' AND tablename = 'action_taken') THEN
    EXECUTE format('
      CREATE TABLE public.action_taken (
        id bigint generated by default as identity primary key,
        horse_id %s not null,
        treatment_id %s not null,
        action_taken_notes text,
        created_at timestamptz not null default now(),
        last_updated timestamptz not null default now(),
        updated_by %s
      )', horses_id_type, treatments_id_type, horses_id_type);
  END IF;

  -- DAILY OBSERVATIONS TABLE
  IF NOT EXISTS (SELECT 1 FROM pg_tables WHERE schemaname = 'public' AND tablename = 'daily_observations') THEN
    EXECUTE format('
      CREATE TABLE public.daily_observations (
        id bigint generated by default as identity primary key,
        horse_id %s,
        notes text,
        todo_status boolean not null default false,
        done_status boolean not null default false,
        notify_staff boolean not null default false,
        created_at timestamptz not null default now(),
        last_updated timestamptz not null default now(),
        updated_by %s
      )', horses_id_type, horses_id_type);
  END IF;

  -- AUDIT LOGS TABLE
  IF NOT EXISTS (SELECT 1 FROM pg_tables WHERE schemaname = 'public' AND tablename = 'audit_logs') THEN
    EXECUTE format('
      CREATE TABLE public.audit_logs (
        id bigint generated by default as identity primary key,
        user_id %s,
        table_name text not null,
        field_name text,
        before_value text,
        after_value text,
        event_time timestamptz not null default now()
      )', horses_id_type);
  END IF;
END $$;

-- Step 1.6: Add foreign key constraints if they don't exist and types match
DO $$ 
DECLARE
  horses_id_type text;
  medical_horse_type text;
  action_horse_type text;
  daily_horse_type text;
  treatments_id_type text;
  action_treatment_type text;
BEGIN
  SELECT data_type INTO horses_id_type
  FROM information_schema.columns
  WHERE table_schema = 'public' AND table_name = 'horses' AND column_name = 'id';

  SELECT data_type INTO treatments_id_type
  FROM information_schema.columns
  WHERE table_schema = 'public' AND table_name = 'treatments' AND column_name = 'id';

  SELECT data_type INTO medical_horse_type
  FROM information_schema.columns
  WHERE table_schema = 'public' AND table_name = 'medical_records' AND column_name = 'horse_id';

  SELECT data_type INTO action_horse_type
  FROM information_schema.columns
  WHERE table_schema = 'public' AND table_name = 'action_taken' AND column_name = 'horse_id';

  SELECT data_type INTO daily_horse_type
  FROM information_schema.columns
  WHERE table_schema = 'public' AND table_name = 'daily_observations' AND column_name = 'horse_id';

  SELECT data_type INTO action_treatment_type
  FROM information_schema.columns
  WHERE table_schema = 'public' AND table_name = 'action_taken' AND column_name = 'treatment_id';

  -- Add FK from medical_records to horses if it doesn't exist and types match
  IF medical_horse_type = horses_id_type AND NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'medical_records_horse_id_fkey'
  ) THEN
    ALTER TABLE public.medical_records 
      ADD CONSTRAINT medical_records_horse_id_fkey 
      FOREIGN KEY (horse_id) REFERENCES public.horses(id) ON DELETE CASCADE;
  END IF;

  -- Add FK from action_taken to horses if it doesn't exist and types match
  IF action_horse_type = horses_id_type AND NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'action_taken_horse_id_fkey'
  ) THEN
    ALTER TABLE public.action_taken 
      ADD CONSTRAINT action_taken_horse_id_fkey 
      FOREIGN KEY (horse_id) REFERENCES public.horses(id) ON DELETE CASCADE;
  END IF;

  -- Add FK from action_taken to treatments if it doesn't exist and types match
  IF action_treatment_type = treatments_id_type AND NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'action_taken_treatment_id_fkey'
  ) THEN
    ALTER TABLE public.action_taken 
      ADD CONSTRAINT action_taken_treatment_id_fkey 
      FOREIGN KEY (treatment_id) REFERENCES public.treatments(id) ON DELETE RESTRICT;
  END IF;

  -- Add FK from daily_observations to horses if it doesn't exist and types match
  IF daily_horse_type = horses_id_type AND NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'daily_observations_horse_id_fkey'
  ) THEN
    ALTER TABLE public.daily_observations 
      ADD CONSTRAINT daily_observations_horse_id_fkey 
      FOREIGN KEY (horse_id) REFERENCES public.horses(id) ON DELETE CASCADE;
  END IF;
END $$;

-- Step 2: Add new columns to users table
ALTER TABLE public.users 
  ADD COLUMN IF NOT EXISTS auth_user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
  ADD COLUMN IF NOT EXISTS email text,
  ADD COLUMN IF NOT EXISTS role user_role DEFAULT 'viewer';

-- Step 3: Migrate existing data (map old boolean fields to new role)
-- Administrators get 'administrator' role
UPDATE public.users 
SET role = 'administrator' 
WHERE administrator = true AND role IS NULL;

-- Editors get 'editor' role (if they have edit_capabilities but aren't admins)
UPDATE public.users 
SET role = 'editor' 
WHERE edit_capabilities = true AND administrator = false AND role IS NULL;

-- Everyone else gets 'viewer' role
UPDATE public.users 
SET role = 'viewer' 
WHERE role IS NULL;

-- Step 4: Make role column not null after data migration
ALTER TABLE public.users 
  ALTER COLUMN role SET NOT NULL;

-- Step 5: Add unique constraint
ALTER TABLE public.users 
  ADD CONSTRAINT users_auth_user_id_key UNIQUE (auth_user_id);

ALTER TABLE public.users 
  ADD CONSTRAINT users_email_key UNIQUE (email);

-- Step 6: Drop old columns (optional - uncomment if you want to remove them)
-- ALTER TABLE public.users 
--   DROP COLUMN IF EXISTS administrator,
--   DROP COLUMN IF EXISTS edit_capabilities,
--   DROP COLUMN IF EXISTS view_capabilities;

-- Step 7: Drop old policies (only if tables exist)
DO $$ 
BEGIN
  -- Drop policies only if the tables exist
  IF EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'users') THEN
    DROP POLICY IF EXISTS "Allow full access to users" ON public.users;
  END IF;
  
  IF EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'horses') THEN
    DROP POLICY IF EXISTS "Allow full access to horses" ON public.horses;
  END IF;
  
  IF EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'medical_records') THEN
    DROP POLICY IF EXISTS "Allow full access to medical_records" ON public.medical_records;
  END IF;
  
  IF EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'treatments') THEN
    DROP POLICY IF EXISTS "Allow full access to treatments" ON public.treatments;
  END IF;
  
  IF EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'action_taken') THEN
    DROP POLICY IF EXISTS "Allow full access to action_taken" ON public.action_taken;
  END IF;
  
  IF EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'daily_observations') THEN
    DROP POLICY IF EXISTS "Allow full access to daily_observations" ON public.daily_observations;
  END IF;
  
  IF EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'audit_logs') THEN
    DROP POLICY IF EXISTS "Allow full access to audit_logs" ON public.audit_logs;
  END IF;
END $$;

-- Step 8: Create helper function
CREATE OR REPLACE FUNCTION public.get_user_role()
RETURNS user_role AS $$
  SELECT role FROM public.users WHERE auth_user_id = auth.uid()
$$ LANGUAGE sql SECURITY DEFINER;

-- Step 9: Create new RLS policies

-- Enable RLS on all tables
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.horses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.medical_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.treatments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.action_taken ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.daily_observations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;

-- Users table policies
DROP POLICY IF EXISTS "Users can view their own data" ON public.users;
CREATE POLICY "Users can view their own data" ON public.users
  FOR SELECT USING (auth.uid() = auth_user_id);

DROP POLICY IF EXISTS "Administrators can manage all users" ON public.users;
CREATE POLICY "Administrators can manage all users" ON public.users
  FOR ALL USING (public.get_user_role() = 'administrator');

-- Horses table policies  
DROP POLICY IF EXISTS "Anyone authenticated can view horses" ON public.horses;
CREATE POLICY "Anyone authenticated can view horses" ON public.horses
  FOR SELECT USING (auth.uid() IS NOT NULL);

DROP POLICY IF EXISTS "Editors and admins can insert horses" ON public.horses;
CREATE POLICY "Editors and admins can insert horses" ON public.horses
  FOR INSERT WITH CHECK (public.get_user_role() IN ('editor', 'administrator'));

DROP POLICY IF EXISTS "Editors and admins can update horses" ON public.horses;
CREATE POLICY "Editors and admins can update horses" ON public.horses
  FOR UPDATE USING (public.get_user_role() IN ('editor', 'administrator'));

DROP POLICY IF EXISTS "Only administrators can delete horses" ON public.horses;
CREATE POLICY "Only administrators can delete horses" ON public.horses
  FOR DELETE USING (public.get_user_role() = 'administrator');

-- Medical records policies
DROP POLICY IF EXISTS "Anyone authenticated can view medical records" ON public.medical_records;
CREATE POLICY "Anyone authenticated can view medical records" ON public.medical_records
  FOR SELECT USING (auth.uid() IS NOT NULL);

DROP POLICY IF EXISTS "Editors and admins can insert medical records" ON public.medical_records;
CREATE POLICY "Editors and admins can insert medical records" ON public.medical_records
  FOR INSERT WITH CHECK (public.get_user_role() IN ('editor', 'administrator'));

DROP POLICY IF EXISTS "Editors and admins can update medical records" ON public.medical_records;
CREATE POLICY "Editors and admins can update medical records" ON public.medical_records
  FOR UPDATE USING (public.get_user_role() IN ('editor', 'administrator'));

DROP POLICY IF EXISTS "Only administrators can delete medical records" ON public.medical_records;
CREATE POLICY "Only administrators can delete medical records" ON public.medical_records
  FOR DELETE USING (public.get_user_role() = 'administrator');

-- Treatments policies
DROP POLICY IF EXISTS "Anyone authenticated can view treatments" ON public.treatments;
CREATE POLICY "Anyone authenticated can view treatments" ON public.treatments
  FOR SELECT USING (auth.uid() IS NOT NULL);

DROP POLICY IF EXISTS "Editors and admins can insert treatments" ON public.treatments;
CREATE POLICY "Editors and admins can insert treatments" ON public.treatments
  FOR INSERT WITH CHECK (public.get_user_role() IN ('editor', 'administrator'));

DROP POLICY IF EXISTS "Editors and admins can update treatments" ON public.treatments;
CREATE POLICY "Editors and admins can update treatments" ON public.treatments
  FOR UPDATE USING (public.get_user_role() IN ('editor', 'administrator'));

DROP POLICY IF EXISTS "Only administrators can delete treatments" ON public.treatments;
CREATE POLICY "Only administrators can delete treatments" ON public.treatments
  FOR DELETE USING (public.get_user_role() = 'administrator');

-- Action taken policies
DROP POLICY IF EXISTS "Anyone authenticated can view actions taken" ON public.action_taken;
CREATE POLICY "Anyone authenticated can view actions taken" ON public.action_taken
  FOR SELECT USING (auth.uid() IS NOT NULL);

DROP POLICY IF EXISTS "Editors and admins can insert actions taken" ON public.action_taken;
CREATE POLICY "Editors and admins can insert actions taken" ON public.action_taken
  FOR INSERT WITH CHECK (public.get_user_role() IN ('editor', 'administrator'));

DROP POLICY IF EXISTS "Editors and admins can update actions taken" ON public.action_taken;
CREATE POLICY "Editors and admins can update actions taken" ON public.action_taken
  FOR UPDATE USING (public.get_user_role() IN ('editor', 'administrator'));

DROP POLICY IF EXISTS "Only administrators can delete actions taken" ON public.action_taken;
CREATE POLICY "Only administrators can delete actions taken" ON public.action_taken
  FOR DELETE USING (public.get_user_role() = 'administrator');

-- Daily observations policies
DROP POLICY IF EXISTS "Anyone authenticated can view daily observations" ON public.daily_observations;
CREATE POLICY "Anyone authenticated can view daily observations" ON public.daily_observations
  FOR SELECT USING (auth.uid() IS NOT NULL);

DROP POLICY IF EXISTS "Editors and admins can insert daily observations" ON public.daily_observations;
CREATE POLICY "Editors and admins can insert daily observations" ON public.daily_observations
  FOR INSERT WITH CHECK (public.get_user_role() IN ('editor', 'administrator'));

DROP POLICY IF EXISTS "Editors and admins can update daily observations" ON public.daily_observations;
CREATE POLICY "Editors and admins can update daily observations" ON public.daily_observations
  FOR UPDATE USING (public.get_user_role() IN ('editor', 'administrator'));

DROP POLICY IF EXISTS "Only administrators can delete daily observations" ON public.daily_observations;
CREATE POLICY "Only administrators can delete daily observations" ON public.daily_observations
  FOR DELETE USING (public.get_user_role() = 'administrator');

-- Audit logs policies
DROP POLICY IF EXISTS "Anyone authenticated can view audit logs" ON public.audit_logs;
CREATE POLICY "Anyone authenticated can view audit logs" ON public.audit_logs
  FOR SELECT USING (auth.uid() IS NOT NULL);

DROP POLICY IF EXISTS "Editors and admins can insert audit logs" ON public.audit_logs;
CREATE POLICY "Editors and admins can insert audit logs" ON public.audit_logs
  FOR INSERT WITH CHECK (public.get_user_role() IN ('editor', 'administrator'));

-- Step 10: Create trigger to auto-create user profile on signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.users (auth_user_id, email, name, role, active_user)
  VALUES (
    NEW.id,
    NEW.email,
    COALESCE(NEW.raw_user_meta_data->>'name', split_part(NEW.email, '@', 1)),
    'viewer', -- Default role for new users
    true
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Drop trigger if it exists
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;

-- Create trigger
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- Step 11: Remove legacy user_roles table and any dependencies
DROP TABLE IF EXISTS public.user_roles CASCADE;

-- Grant necessary permissions
GRANT USAGE ON SCHEMA public TO anon, authenticated;
GRANT ALL ON ALL TABLES IN SCHEMA public TO anon, authenticated;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated;
