-- backend/db/schema.sql
-- Run this in the Supabase SQL Editor to set up all tables.
-- Column names match frontend types exactly so Supabase returns
-- objects the frontend can consume directly.

-- =========================
-- USER ROLE ENUM
-- =========================
create type user_role as enum ('viewer', 'editor', 'administrator');

-- =========================
-- USERS TABLE
-- =========================
create table if not exists public.users (
  id bigint generated by default as identity primary key,
  auth_user_id uuid references auth.users(id) on delete cascade,
  email text unique,
  name text not null,
  role user_role not null default 'viewer',
  active_user boolean not null default true,
  phone text,
  created_at timestamptz not null default now(),
  last_updated timestamptz not null default now(),
  unique(auth_user_id)
);

-- =========================
-- HORSES TABLE
-- =========================
create table if not exists public.horses (
  id bigint generated by default as identity primary key,
  name text not null,
  breed text,
  birth_year integer check (birth_year >= 1900 and birth_year <= 2100),
  gender text check (gender in ('Mare', 'Gelding')),
  color text,
  photo_url text,
  health_status text not null default 'healthy'
    check (health_status in ('healthy', 'needs_attention', 'critical', 'palliative')),
  arrival_date date,

  -- eye conditions
  left_eye text check (left_eye in ('Missing', 'Blind', 'Glaucoma', 'Injured') or left_eye is null),
  right_eye text check (right_eye in ('Missing', 'Blind', 'Glaucoma', 'Injured') or right_eye is null),

  -- medical conditions
  heart_murmur boolean not null default false,
  cushings_positive boolean not null default false,
  heaves boolean not null default false,
  anhidrosis boolean not null default false,
  shivers boolean not null default false,

  -- behavioral
  bites boolean not null default false,
  kicks boolean not null default false,
  difficult_to_catch boolean not null default false,

  -- care needs
  problem_with_needles boolean not null default false,
  problem_with_farrier boolean not null default false,
  sedation_for_farrier boolean not null default false,
  requires_extra_feed boolean not null default false,
  requires_extra_mash boolean not null default false,

  -- status flags
  seen_by_vet boolean not null default false,
  seen_by_farrier boolean not null default false,
  military_police_horse boolean not null default false,
  ex_racehorse boolean not null default false,
  deceased boolean not null default false,
  date_of_death date,

  -- notes & misc
  grooming_day text,
  pasture text,
  behavior_notes text,
  regular_treatment boolean not null default false,
  medical_notes text,

  -- timestamps
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_updated timestamptz not null default now(),
  updated_by bigint references public.users(id) on delete set null
);

-- =========================
-- MEDICAL RECORDS TABLE
-- =========================
create table if not exists public.medical_records (
  id bigint generated by default as identity primary key,
  horse_id bigint not null references public.horses(id) on delete cascade,
  record_type text not null default 'checkup'
    check (record_type in ('checkup', 'vaccination', 'treatment', 'surgery', 'other')),
  description text not null,
  vet_name text not null,
  date date not null,
  next_followup date,
  notes text,
  created_at timestamptz not null default now()
);

-- =========================
-- TREATMENTS TABLE
-- =========================
create table if not exists public.treatments (
  id bigint generated by default as identity primary key,
  type text not null,
  frequency text,
  created_at timestamptz not null default now(),
  last_updated timestamptz not null default now(),
  updated_by bigint references public.users(id) on delete set null
);

-- =========================
-- ACTION TAKEN TABLE
-- (links horse + treatment)
-- =========================
create table if not exists public.action_taken (
  id bigint generated by default as identity primary key,
  horse_id bigint not null references public.horses(id) on delete cascade,
  treatment_id bigint not null references public.treatments(id) on delete restrict,
  action_taken_notes text,
  created_at timestamptz not null default now(),
  last_updated timestamptz not null default now(),
  updated_by bigint references public.users(id) on delete set null
);

-- =========================
-- DAILY OBSERVATIONS / TO-DO
-- =========================
create table if not exists public.daily_observations (
  id bigint generated by default as identity primary key,
  horse_id bigint references public.horses(id) on delete cascade,
  notes text,
  todo_status boolean not null default false,
  done_status boolean not null default false,
  notify_staff boolean not null default false,
  created_at timestamptz not null default now(),
  last_updated timestamptz not null default now(),
  updated_by bigint references public.users(id) on delete set null
);

-- =========================
-- AUDIT LOGS TABLE
-- =========================
create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  user_id bigint references public.users(id) on delete set null,
  table_name text not null,
  field_name text,
  before_value text,
  after_value text,
  event_time timestamptz not null default now()
);

-- =========================
-- ROW LEVEL SECURITY
-- =========================
alter table public.users enable row level security;
alter table public.horses enable row level security;
alter table public.medical_records enable row level security;
alter table public.treatments enable row level security;
alter table public.action_taken enable row level security;
alter table public.daily_observations enable row level security;
alter table public.audit_logs enable row level security;

-- Helper function to get the current user's role
create or replace function public.get_user_role()
returns user_role as $$
  select role from public.users where auth_user_id = auth.uid()
$$ language sql security definer;

-- Users table policies
create policy "Users can view their own data" on public.users
  for select using (auth.uid() = auth_user_id);

create policy "Administrators can manage all users" on public.users
  for all using (public.get_user_role() = 'administrator');

-- Horses table policies  
create policy "Anyone authenticated can view horses" on public.horses
  for select using (auth.uid() is not null);

create policy "Editors and admins can insert horses" on public.horses
  for insert with check (public.get_user_role() in ('editor', 'administrator'));

create policy "Editors and admins can update horses" on public.horses
  for update using (public.get_user_role() in ('editor', 'administrator'));

create policy "Only administrators can delete horses" on public.horses
  for delete using (public.get_user_role() = 'administrator');

-- Medical records policies
create policy "Anyone authenticated can view medical records" on public.medical_records
  for select using (auth.uid() is not null);

create policy "Editors and admins can insert medical records" on public.medical_records
  for insert with check (public.get_user_role() in ('editor', 'administrator'));

create policy "Editors and admins can update medical records" on public.medical_records
  for update using (public.get_user_role() in ('editor', 'administrator'));

create policy "Only administrators can delete medical records" on public.medical_records
  for delete using (public.get_user_role() = 'administrator');

-- Treatments policies
create policy "Anyone authenticated can view treatments" on public.treatments
  for select using (auth.uid() is not null);

create policy "Editors and admins can insert treatments" on public.treatments
  for insert with check (public.get_user_role() in ('editor', 'administrator'));

create policy "Editors and admins can update treatments" on public.treatments
  for update using (public.get_user_role() in ('editor', 'administrator'));

create policy "Only administrators can delete treatments" on public.treatments
  for delete using (public.get_user_role() = 'administrator');

-- Action taken policies
create policy "Anyone authenticated can view actions taken" on public.action_taken
  for select using (auth.uid() is not null);

create policy "Editors and admins can insert actions taken" on public.action_taken
  for insert with check (public.get_user_role() in ('editor', 'administrator'));

create policy "Editors and admins can update actions taken" on public.action_taken
  for update using (public.get_user_role() in ('editor', 'administrator'));

create policy "Only administrators can delete actions taken" on public.action_taken
  for delete using (public.get_user_role() = 'administrator');

-- Daily observations policies
create policy "Anyone authenticated can view daily observations" on public.daily_observations
  for select using (auth.uid() is not null);

create policy "Editors and admins can insert daily observations" on public.daily_observations
  for insert with check (public.get_user_role() in ('editor', 'administrator'));

create policy "Editors and admins can update daily observations" on public.daily_observations
  for update using (public.get_user_role() in ('editor', 'administrator'));

create policy "Only administrators can delete daily observations" on public.daily_observations
  for delete using (public.get_user_role() = 'administrator');

-- Audit logs policies (read-only for all authenticated users)
create policy "Anyone authenticated can view audit logs" on public.audit_logs
  for select using (auth.uid() is not null);

create policy "Editors and admins can insert audit logs" on public.audit_logs
  for insert with check (public.get_user_role() in ('editor', 'administrator'));
