-- backend/db/schema.sql

-- 1. Horses Table
create table if not exists public.horses (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  breed text,
  age integer,
  description text,
  owner_id uuid references auth.users(id)
);

-- 2. Medical Records Table
create table if not exists public.medical_records (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  horse_id bigint references public.horses(id) on delete cascade,
  date date not null,
  notes text
);

-- 3. Enable Security (RLS)
alter table public.horses enable row level security;
alter table public.medical_records enable row level security;

-- 4. Allow public read access (So your seed script works immediately)
create policy "Allow public read access" on public.horses for select using (true);
create policy "Allow public insert access" on public.horses for insert with check (true);
create policy "Allow public read access" on public.medical_records for select using (true);
create policy "Allow public insert access" on public.medical_records for insert with check (true);