-- backend/db/schema.sql
-- Run this in the Supabase SQL Editor to set up all tables.
-- Column names match frontend types exactly so Supabase returns
-- objects the frontend can consume directly.

-- =========================
-- USERS TABLE
-- =========================
create table if not exists public.users (
  id bigint generated by default as identity primary key,
  name text not null,
  administrator boolean not null default false,
  edit_capabilities boolean not null default false,
  view_capabilities boolean not null default true,
  active_user boolean not null default true,
  phone text,
  created_at timestamptz not null default now(),
  last_updated timestamptz not null default now()
);

-- =========================
-- HORSES TABLE
-- =========================
create table if not exists public.horses (
  id bigint generated by default as identity primary key,
  name text not null,
  breed text,
  birth_year integer check (birth_year >= 1900 and birth_year <= 2100),
  gender text check (gender in ('Mare', 'Gelding')),
  color text,
  photo_url text,
  health_status text not null default 'healthy'
    check (health_status in ('healthy', 'needs_attention', 'critical', 'palliative')),
  arrival_date date,

  -- eye conditions
  left_eye text check (left_eye in ('Missing', 'Blind', 'Glaucoma', 'Injured') or left_eye is null),
  right_eye text check (right_eye in ('Missing', 'Blind', 'Glaucoma', 'Injured') or right_eye is null),

  -- medical conditions
  heart_murmur boolean not null default false,
  cushings_positive boolean not null default false,
  heaves boolean not null default false,
  anhidrosis boolean not null default false,
  shivers boolean not null default false,

  -- behavioral
  bites boolean not null default false,
  kicks boolean not null default false,
  difficult_to_catch boolean not null default false,

  -- care needs
  problem_with_needles boolean not null default false,
  problem_with_farrier boolean not null default false,
  sedation_for_farrier boolean not null default false,
  requires_extra_feed boolean not null default false,
  requires_extra_mash boolean not null default false,

  -- status flags
  seen_by_vet boolean not null default false,
  seen_by_farrier boolean not null default false,
  military_police_horse boolean not null default false,
  ex_racehorse boolean not null default false,
  deceased boolean not null default false,
  date_of_death date,

  -- notes & misc
  grooming_day text,
  pasture text,
  behavior_notes text,
  regular_treatment boolean not null default false,
  medical_notes text,

  -- timestamps
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_updated timestamptz not null default now(),
  updated_by bigint references public.users(id) on delete set null
);

-- =========================
-- MEDICAL RECORDS TABLE
-- =========================
create table if not exists public.medical_records (
  id bigint generated by default as identity primary key,
  horse_id bigint not null references public.horses(id) on delete cascade,
  record_type text not null default 'checkup'
    check (record_type in ('checkup', 'vaccination', 'treatment', 'surgery', 'other')),
  description text not null,
  vet_name text not null,
  date date not null,
  next_followup date,
  notes text,
  created_at timestamptz not null default now()
);

-- =========================
-- TREATMENTS TABLE
-- =========================
create table if not exists public.treatments (
  id bigint generated by default as identity primary key,
  type text not null,
  frequency text,
  created_at timestamptz not null default now(),
  last_updated timestamptz not null default now(),
  updated_by bigint references public.users(id) on delete set null
);

-- =========================
-- ACTION TAKEN TABLE
-- (links horse + treatment)
-- =========================
create table if not exists public.action_taken (
  id bigint generated by default as identity primary key,
  horse_id bigint not null references public.horses(id) on delete cascade,
  treatment_id bigint not null references public.treatments(id) on delete restrict,
  action_taken_notes text,
  created_at timestamptz not null default now(),
  last_updated timestamptz not null default now(),
  updated_by bigint references public.users(id) on delete set null
);

-- =========================
-- DAILY OBSERVATIONS / TO-DO
-- =========================
create table if not exists public.daily_observations (
  id bigint generated by default as identity primary key,
  horse_id bigint references public.horses(id) on delete cascade,
  notes text,
  todo_status boolean not null default false,
  done_status boolean not null default false,
  notify_staff boolean not null default false,
  created_at timestamptz not null default now(),
  last_updated timestamptz not null default now(),
  updated_by bigint references public.users(id) on delete set null
);

-- =========================
-- AUDIT LOGS TABLE
-- =========================
create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  user_id bigint references public.users(id) on delete set null,
  table_name text not null,
  field_name text,
  before_value text,
  after_value text,
  event_time timestamptz not null default now()
);

-- =========================
-- ROW LEVEL SECURITY
-- =========================
alter table public.users enable row level security;
alter table public.horses enable row level security;
alter table public.medical_records enable row level security;
alter table public.treatments enable row level security;
alter table public.action_taken enable row level security;
alter table public.daily_observations enable row level security;
alter table public.audit_logs enable row level security;

-- Allow full access via the service/anon key (no auth yet)
create policy "Allow full access to users" on public.users
  for all using (true) with check (true);

create policy "Allow full access to horses" on public.horses
  for all using (true) with check (true);

create policy "Allow full access to medical_records" on public.medical_records
  for all using (true) with check (true);

create policy "Allow full access to treatments" on public.treatments
  for all using (true) with check (true);

create policy "Allow full access to action_taken" on public.action_taken
  for all using (true) with check (true);

create policy "Allow full access to daily_observations" on public.daily_observations
  for all using (true) with check (true);

create policy "Allow full access to audit_logs" on public.audit_logs
  for all using (true) with check (true);
